### ISSUE TITLE
WISECONDOR-OUTPUT issues

### ISSUE THREAD

**Issue by Manonanthini** [rstraver/wisecondor#16]
I have finished gc correction of sample using gcc.py. What might be the next step to proceed?

**Comment by rstraver** [comment]
Have you checked the wiki? There is a guided pipeline there and a new script called run.sh in the latest version:
https://github.com/rstraver/wisecondor/wiki/Example-Pipeline
https://github.com/rstraver/wisecondor/wiki/WISECONDOR-on-autopilot%3A-run.sh

**Comment by Manonanthini** [comment]
Hi Rstraver,
I have created gccountperbin.pickle,reftable.pickle and also sample.pickle.
While running the command ,
python test.py sample.pickle gccountperbin.pickle reftable.pickle sample.plot
I am getting errors inlines 44 and 35...and i am not able to run the command to 
view the ouput.

Thanks,
Mano

**Comment by rstraver** [comment]
Could you copy-paste the exact errors you get?

Also, is your reftable.pickle created on several gc-corrected reference samples? 
Additionally, check if your reference samples have the .gcc extension instead of .pickle after gc-correction, I believe the ref table creation only uses files with this extension.

**Comment by rstraver** [comment]
Considering the time since last contact I'll just close this issue. If your problem was not resolved feel free to re-open the issue.
